### ISSUE TITLE
ICurrentSearch Store development

### ISSUE THREAD

**Issue by plastikaweb** [adab1ts/veinapp#11]
This is a subtask of #4 

Development of the store from geocoding input.

The State: `ICurrentSearch {
  name: string;
  lat: number;
  long: number;
}`

**Comment by zuzust** [comment]
Bear in mind Angular Style Guide (https://angular.io/styleguide#!#03-03) :wink:

**Comment by plastikaweb** [comment]
One user case:
The search returns **no result**. How we have to deal with it?

I can imagine two posible responses:

1. We simply store the no results search as a state. So, in the view the previous search list and map locators dissapear and a warning with 'NO_RESULTS' is displayed.
2. We does not change the state, so the previous search is maintained and the view for the list and map locators remains unchanged. A warning with 'NO_RESULTS' is displayed.

My personal preference: Option 2.
What do you think @zuzust @sgimeno @laklau ?

**Comment by zuzust** [comment]
I agree with you @plastikaweb. In this scenario no geosearch is triggered, so the front shouldn't react as no change to the list of places is performed. No change to the centre of the previous search should be performed neither. The only decision to make is where in the UI should appear the message. Let's see what @sgimeno has to say.
