### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by zuzust** [adab1ts/veinapp#13]
There is something wrong with testing configuration. We must try to fix it as soon as possible. @sgimeno would you please check it out?

**Comment by plastikaweb** [comment]
As we talked @zuzust , it is caused by the injection of a service (AngularFire2) in the main component. Any injection must be provide in the test as in the correspondent development module.

**Comment by plastikaweb** [comment]
I've done 2 tests on geocoding services (see PR #14) @zuzust @sgimeno that are working ok.
I've reverted changes on the test.ts file as we talked this morning @zuzust .

**Comment by zuzust** [comment]
A quick aside @plastikaweb, remember @sgimeno's proposal of conversation: two comments from the same person should merge in a single comment by editing the last one :wink:.

Now, then something is wrong with my development setup, because having reverted changes to `test.ts`, `karma` fails to exit and Chrome remains launched. I have to finish the process closing Chrome window 3 times.

I am on it. But let me ask you, have you got the packages' versions defined in `package.json`? And which `node` and `npm` versions are you using?

**Comment by plastikaweb** [comment]
Yes, I've got the packages installed and updated and of course the same versions that appear in `package.json.` 

My versions:
```
Node v7.2.0
```
```
npm 4.0.2

```
Anyway see the comments I've put about this issue in PR #14.
