### ISSUE TITLE
Update Covalent UI core library to beta.2

### ISSUE THREAD

**Issue by zuzust** [adab1ts/veinapp#15]
It seems there is a bug in @covalent/core that prevents building for production.

See Teradata/covalent#319

Covalent beta.2 is out!

Further info: https://github.com/Teradata/covalent/blob/develop/docs/CHANGELOG.md#100-beta2-hotel-california-2017-02-23

**Comment by plastikaweb** [comment]
Would be it possible to add the next core changes when you do the PR?
- In angular-cli.json, change the styles attribute:
`"styles": [
        "../node_modules/@covalent/core/common/platform.scss",
        "theme.scss",
        "styles.scss"
      ],`

- In .gitignore add:
`/scripts/*.js or /**/*.js`
