### ISSUE TITLE
Map selected place behavior

### ISSUE THREAD

**Issue by plastikaweb** [adab1ts/veinapp#39]
- On select a place in list items (change state for search.currentPlace), the marker in map is updated adding a new marker over the normal one if possible or changing the marker with a new one (that can emulate two icons in one).
- On select a marker on map repeats the behavior adding a new marker, and changes state for search.selectedPlace and triggers the routing to the correspondent detail view.
- The selectedPlace should re-center the map position to it.

- add popup (http://leafletjs.com/reference-1.0.3.html#popup) (? @zuzust )
- Update the markers on map both for center and near places. (pending @laklau )
- Add title and alt attrs (http://leafletjs.com/reference-1.0.3.html#marker)
---------------------

- View names of places near the marker (study)
- Mark clustering (https://github.com/Leaflet/Leaflet.markercluster)

**Comment by zuzust** [comment]
@plastikaweb no popup wanted.
