### ISSUE TITLE
Sidenav width too narrow

### ISSUE THREAD

**Issue by zuzust** [adab1ts/veinapp#44]
Sidenav width should be wider to show complete place address.

**Comment by plastikaweb** [comment]
Some comments:
- Some places names are in uppercase. In lowercase width would be reduced.
- What would be a correct width? We have no security that this would be always enough for any cases.
- Now it has 300px width (on >= 600px screen size). See at 600px:
![captura de pantalla 2017-03-15 16 27 51](https://cloud.githubusercontent.com/assets/5324001/23956272/8cf8f78a-099c-11e7-98d6-110156338749.png)

Just to say that it needs a more reflexive consideration to apply some solution besides increasing the width by x px.

**Comment by zuzust** [comment]
Already done.
