### ISSUE TITLE
DB populate script fails to capitalize places names

### ISSUE THREAD

**Issue by zuzust** [adab1ts/veinapp#52]
Places names are not afected by capitalizer function.

**Comment by plastikaweb** [comment]
I've removed all the data from firebase and run the script twice (one with the -p flag) and I see the the names correctly capitalized. Could you give more info?

Attached an export JSON file from firebase after script running.
[quick-start-c61e4-export.json.zip](https://github.com/adab1ts/veinapp/files/852274/quick-start-c61e4-export.json.zip)

**Comment by plastikaweb** [comment]
@zuzust Any new comment about this item?

**Comment by zuzust** [comment]
@plastikaweb Not yet. We have to wait until being delivered the new data.
